"""empty message

Revision ID: 536d9a1409cc
Revises: 37f270c0f258
Create Date: 2021-06-22 01:53:39.562457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536d9a1409cc'
down_revision = '37f270c0f258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Artist', ['name'])
    op.create_unique_constraint(None, 'Venue', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    # ### end Alembic commands ###
