"""empty message

Revision ID: 6274b64e06b4
Revises: a96d17c301a3
Create Date: 2021-06-20 18:38:12.828238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6274b64e06b4'
down_revision = 'a96d17c301a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('looking_for_venues', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'looking_for_venues')
    op.drop_column('Artist', 'website_link')
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###
