"""empty message

Revision ID: 806129eb62be
Revises: 6274b64e06b4
Create Date: 2021-06-20 18:54:14.572655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806129eb62be'
down_revision = '6274b64e06b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'address')
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    op.add_column('Artist', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
